### ISSUE TITLE
How do I stop ViaVersion from checking the server version?

### ISSUE THREAD

**Issue by CactiChameleon9** [ViaVersion/ViaVersion#1913]
ViaVersion with velocity 1.10 does not get the correct version for cuberite. I am trying to force it to think it is 1.12.2... but It always says that `ViaVersion detected server version: 1.7-1.7.5(4)`

My config, I think, should disable this check... but it does not:
```
velocity-ping-interval: -1
velocity-ping-save: false
velocity-servers:
  default: 340
  lobby: 340
```

Even if I stop the server and then start velocity without the server running it still ignores settings....
